dnl This file generated by the ROSE build script.
AC_DEFUN([ROSE_OPTIONAL_PROJECTS],[
OPTIONAL_PROJECTS=
AC_SUBST(OPTIONAL_PROJECTS)


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/AMReX-Translation/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/AMReX-Translation])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS AMReX-Translation"

dnl List of all makefiles for this project              -*- autoconf -*-
AC_CONFIG_FILES(projects/AMReX-Translation/Makefile)

AC_CONFIG_FILES([projects/AMReX-Translation/AmrexF2Cxx.sh:projects/AMReX-Translation/AmrexF2Cxx.sh], [chmod ugo+x projects/AMReX-Translation/AmrexF2Cxx.sh])
AC_CONFIG_FILES([projects/AMReX-Translation/support/include/amrex.hpp:projects/AMReX-Translation/support/include/amrex.hpp])
AC_CONFIG_FILES([projects/AMReX-Translation/support/blueprint/empty_cxx_amrex.cc:projects/AMReX-Translation/support/blueprint/empty_cxx_amrex.cc])




dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/BinaryAnalysisTools/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/BinaryAnalysisTools])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS BinaryAnalysisTools"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/BinaryAnalysisTools/Makefile)

# script files will be copied over to the build directory (PP 11/09/19)
# AC_CONFIG_FILES([projects/BinaryAnalysisTools/rose-execution-monitor-linux-perf-intel-x86_64.sh:projects/BinaryAnalysisTools/rose-execution-monitor-linux-perf-intel-x86_64.sh], [chmod ugo+x projects/BinaryAnalysisTools/rose-execution-monitor-linux-perf-intel-x86_64.sh])

dnl The bROwSE tool depends on Wt (web toolkit)
AC_ARG_WITH(
    [wt],
    AS_HELP_STRING(
        [--with-wt=PREFIX],
        [Use the Wt web toolkit available from https://webtoolkit.eu/wt. The PREFIX, if specified,
	 should be the prefix used to install Wt, such as "/usr/local". The default is the empty prefix,
	 in which case the headers and library must be installed in a place where they will be found.
	 Saying "no" for the prefix is the same as saying "--without-wt".]),
	[AC_DEFINE(ROSE_USE_WT, 1, [Defined if the web toolkit Wt is available.])
	 if test "$with_wt" = "yes"; then WT_PREFIX=/usr; else WT_PREFIX="$with_wt"; fi],
	[with_wt=no])
AC_SUBST(WT_PREFIX)
AM_CONDITIONAL(ROSE_USE_WT, test "$with_wt" != "no")


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/CodeProperties/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/CodeProperties])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS CodeProperties"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES([projects/CodeProperties/Makefile])

dnl Even if this project is present in ROSE's "projects" directory, we might not have the prerequisites to compile
dnl this project.  Enable the project's makefiles by using the ROSE_ENABLE_projectname automake conditional.
dnl Many prerequisites have probably already been tested by ROSE's main configure script, so we don't need to list
dnl them here again (although it usually doesn't hurt).
AC_MSG_CHECKING([whether CodeProperties project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_code_properties=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_CODE_PROPERTIES], [test "$rose_enable_project_code_properties" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/CodeThorn/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/CodeThorn])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS CodeThorn"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/CodeThorn/Makefile
		projects/CodeThorn/src/Makefile])

AC_MSG_CHECKING([whether CodeThorn project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_CodeThorn=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_CODETHORN], [test "$rose_enable_project_CodeThorn" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/MatlabTranslation/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/MatlabTranslation])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS MatlabTranslation"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/MatlabTranslation/Makefile)
AC_CONFIG_FILES(projects/MatlabTranslation/src/Makefile)
AC_CONFIG_FILES(projects/MatlabTranslation/tests/Makefile)

AC_CONFIG_FILES([projects/MatlabTranslation/M2Cxx.sh:projects/MatlabTranslation/M2Cxx.sh], [chmod ugo+x projects/MatlabTranslation/M2Cxx.sh])
AC_CONFIG_FILES([projects/MatlabTranslation/support/armadillo/builtins.h:projects/MatlabTranslation/support/armadillo/builtins.h])
AC_CONFIG_FILES([projects/MatlabTranslation/support/armadillo/fastnumerics.h:projects/MatlabTranslation/support/armadillo/fastnumerics.h])
AC_CONFIG_FILES([projects/MatlabTranslation/support/armadillo/Matrix.h:projects/MatlabTranslation/support/armadillo/Matrix.h])
AC_CONFIG_FILES([projects/MatlabTranslation/support/cxx-stub/builtins.h:projects/MatlabTranslation/support/cxx-stub/builtins.h])
AC_CONFIG_FILES([projects/MatlabTranslation/support/cxx-stub/fastnumerics.h:projects/MatlabTranslation/support/cxx-stub/fastnumerics.h])
AC_CONFIG_FILES([projects/MatlabTranslation/support/cxx-stub/Matrix.h:projects/MatlabTranslation/support/cxx-stub/Matrix.h])
AC_CONFIG_FILES([projects/MatlabTranslation/support/matlab/builtins.m:projects/MatlabTranslation/support/matlab/builtins.m])
AC_CONFIG_FILES([projects/MatlabTranslation/support/blueprint/Makefile.default:projects/MatlabTranslation/support/blueprint/Makefile.default])


AC_ARG_WITH(armadillo,
	[  --with-armadillo[=PATH]   Installation prefix for optional Armadillo library (>= 7.950.0) (for Matlab to C++ translation - requires Matlab frontend enabled).],
	[AC_DEFINE(ROSE_MATLAB_USE_ARMADILLO, 1, [Defined if the Armadillo library is available.])
	 if test "$with_armadillo" = "yes"; then ARMA_PREFIX=/usr; else ARMA_PREFIX="$with_armadillo"; fi],
	[with_armadillo=no])
AC_SUBST(ARMA_PREFIX)
AM_CONDITIONAL(ROSE_MATLAB_USE_ARMADILLO, test "$with_armadillo" != "no")


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/MatrixTesting/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/MatrixTesting])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS MatrixTesting"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(
    projects/MatrixTesting/Makefile
    projects/MatrixTesting/src/Makefile)

dnl The matrix query tool depends on Wt (web toolkit)
AC_ARG_WITH(wt,
	[  --with-wt=PATH   Installation prefix for optional Wt (web toolkit) library.],
	[AC_DEFINE(ROSE_USE_WT, 1, [Defined if the web toolkit Wt is available.])
	 if test "$with_wt" = "yes"; then WT_PREFIX=/usr; else WT_PREFIX="$with_wt"; fi],
	[with_wt=no])
AC_SUBST(WT_PREFIX)
AM_CONDITIONAL(ROSE_USE_WT, test "$with_wt" != "no")


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/OpenK/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/OpenK])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS OpenK"

dnl List of all makefiles for this project
AC_CONFIG_FILES([projects/OpenK/Makefile
                 projects/OpenK/knowledgeBuilder/Makefile]) 


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/Rose-To-LLVM/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/Rose-To-LLVM])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS Rose-To-LLVM"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/Rose-To-LLVM/Makefile
		projects/Rose-To-LLVM/src/Makefile
		projects/Rose-To-LLVM/tests/Makefile
		projects/Rose-To-LLVM/src/rosetollvm/Makefile])

AC_MSG_CHECKING([whether Rose-To-LLVM project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_Rose_To_LLVM=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_Rose_To_LLVM], [test "$rose_enable_project_Rose_To_LLVM" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/RTC2/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/RTC2])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS RTC2"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/RTC2/Makefile)
AC_CONFIG_FILES(projects/RTC2/src/Makefile)
AC_CONFIG_FILES(projects/RTC2/tests/Makefile)

AC_CONFIG_FILES([projects/RTC2/tests/chk.sh:projects/RTC2/tests/chk.sh], [chmod ugo+x projects/RTC2/tests/chk.sh])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/scalarization/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/scalarization])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS scalarization"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/scalarization/Makefile
		projects/scalarization/src/Makefile
		projects/scalarization/tests/Makefile])

AC_MSG_CHECKING([whether scalarization project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_scalarization=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_SCALARIZATION], [test "$rose_enable_project_scalarization" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/simulator2/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/simulator2])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS simulator2"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/simulator2/Makefile)


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/SnippetTools/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/SnippetTools])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS SnippetTools"

dnl List of all makefiles for this project							-*- autoconf -*-
AC_CONFIG_FILES(projects/SnippetTools/Makefile)


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/TALCDataLayout/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/TALCDataLayout])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS TALCDataLayout"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/TALCDataLayout/Makefile
		projects/TALCDataLayout/src/Makefile
		projects/TALCDataLayout/src/haopt/Makefile
		projects/TALCDataLayout/src/main/Makefile
		projects/TALCDataLayout/src/meta/Makefile
		projects/TALCDataLayout/src/modules/Makefile
		projects/TALCDataLayout/src/runtime/Makefile
		projects/TALCDataLayout/src/utilities/Makefile
		projects/TALCDataLayout/tests/Makefile])

dnl Even if this project is present in ROSE's "projects" directory, we might not have the prerequisites to compile
dnl this project.  Enable the project's makefiles by using the ROSE_ENABLE_projectname automake conditional.
dnl Many prerequisites have probably already been tested by ROSE's main configure script, so we don't need to list
dnl them here again (although it usually doesn't hurt).
AC_MSG_CHECKING([whether TALCDataLayout project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_talcdatalayout=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_TALCDATALAYOUT], [test "$rose_enable_project_talcdatalayout" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/traceAnalysis/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/traceAnalysis])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS traceAnalysis"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/traceAnalysis/Makefile])

dnl Even if this project is present in ROSE's "projects" directory, we might not have the prerequisites to compile
dnl this project.  Enable the project's makefiles by using the ROSE_ENABLE_projectname automake conditional.
dnl Many prerequisites have probably already been tested by ROSE's main configure script, so we don't need to list
dnl them here again (although it usually doesn't hurt).
AC_MSG_CHECKING([whether traceAnalysis project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_trace_analysis=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_TRACE_ANALYSIS], [test "$rose_enable_project_trace_analysis" = yes])


dnl -----------------------------------------------------------------------------------------------------
dnl -- This part of the file comes from projects/ZFPTool/rose.config
dnl -----------------------------------------------------------------------------------------------------
AC_MSG_NOTICE([configuring optional projects/ZFPTool])
OPTIONAL_PROJECTS="$OPTIONAL_PROJECTS ZFPTool"

dnl List of all makefiles for this project						-*- autoconf -*-
AC_CONFIG_FILES([projects/ZFPTool/Makefile
		projects/ZFPTool/src/Makefile
		projects/ZFPTool/tests/Makefile])

AC_MSG_CHECKING([whether ZFPTool project prerequisites are satisfied])
AC_MSG_RESULT([yes])
rose_enable_project_ZFPTool=yes

AM_CONDITIONAL([ROSE_ENABLE_PROJECT_SCALARIZATION], [test "$rose_enable_project_ZFPTool" = yes])
])
